// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                    uuid.UUID
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamp
	UserAgent             string
	IpAddress             string
	IsActive              bool
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
}
