// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                    pgtype.UUID
	RefreshTokenHash      pgtype.Text
	RefreshTokenExpiresAt pgtype.Timestamp
	UserAgent             pgtype.Text
	IpAddress             pgtype.Text
	IsActive              pgtype.Bool
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
}
